# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CSC 448 Bioinformatics Algorithms | COVID-19 Blog
email:
description: >- # this means to ignore newlines until "baseurl:"
  As part of CSC 448 Bioinformatics Algorithms at Cal Poly, we will be researching and analyzing the latest novel coronavirus data on a weekly basis.
twitter_username: "sarahkurd"
github_username: "sarahkurd"
minimal_mistakes_skin: dark
search: true
url: "https://anderson-github-classroom.github.io/"
baseurl: "/csc-448-project"
repository: "anderson-github-classroom/csc-448-project"
breadcrumbs: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 4 # amount of posts to show
paginate_path: /page:num/
timezone: America/Los_Angeles

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Sarah Kurdoghlian"
  avatar : "/assets/images/bishop.jpg"
  bio    : |
    The purpose of this site is to aggregate research and practice bioinformatic analysis for COVID-19.
    Conducted as a part of CSC 448 at Cal Poly.
    [**csc-448-project**](https://github.com/anderson-github-classroom/csc-448-project) is maintained by [**anderson-github-classroom**](https://github.com/anderson-github-classroom).
  location: "San Luis Obispo, CA"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sarahkurd"


footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      # comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
